# Generated by Django 5.1 on 2024-09-02 21:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('socio_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(1000000)])),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('fec_nac', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('localidad', models.CharField(max_length=100)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('dependencia', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('funcion', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio_laboral', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_laboral', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('S', 'Suspendido'), ('B', 'Baja')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caracter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.caracter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socio_created_by', to=settings.AUTH_USER_MODEL)),
                ('estado_civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.estadocivil')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socio_modified_by', to=settings.AUTH_USER_MODEL)),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_familiar', models.IntegerField()),
                ('apellido_familiar', models.CharField(max_length=100)),
                ('nombre_familiar', models.CharField(max_length=100)),
                ('parentesco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.parentesco')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socio')),
            ],
        ),
    ]
