# Generated by Django 5.1 on 2024-09-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_alter_socio_celular_alter_socio_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='telefono_laboral',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
